
# Use containers.
sudo: false

dist: xenial

language: python

python:
  - 2.7
  - 3.6
  
install:
  - pip install --upgrade pip
  - pip install numpy
  - pip install pytest
  - pip install scipy
  
script:
  - python setup.py install
  - pytest
